firstname = input("Enter your firstname")
surname= input("Enter your surname")
age = input("Enter your age")
subject = input("Enter your favourite subject")
print(firstname)
print(surname)
print(age)
print(subject)
